apiVersion: apps/v1
kind: Deployment
metadata:
  name: swiggy-app
  labels:
    app: swiggy-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: swiggy-app
  template:
    metadata:
      labels:
        app: swiggy-app
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: swiggy-app
        image: nehakyatham/swiggy-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80   # NGINX SERVES ON PORT 80 NOW
---
apiVersion: v1
kind: Service
metadata:
  name: swiggy-app
  labels:
    app: swiggy-app
spec:
  type: LoadBalancer
  selector:
    app: swiggy-app
  ports:
  - port: 80
    targetPort: 80   # MUST MATCH NGINX PORT
