name: Build

on:
  push:
    branches:
      - main

jobs:

  build-analyze-scan:
    name: Build, Analyze & Scan
    runs-on: [self-hosted]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Trivy FS Scan
        run: trivy fs . > trivyfs.txt

      - name: Docker Build and Push
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: nehakyatham/swiggy-app
          tags: latest
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Trivy Image Scan
        run: trivy image nehakyatham/swiggy-app > trivyimage.txt

      - name: Send a Slack Notification
        if: always()
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: 'channel-git-actions'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  deploy:
    name: Deploy to Kubernetes
    needs: build-analyze-scan
    runs-on: [self-hosted]

    steps:
      - name: Update kubeconfig
        run: aws eks --region eu-west-2 update-kubeconfig --name nehabox-cluster

      - name: Deploy to Kubernetes
        run: kubectl apply -f deployment-and-service.yml
        
      - name: Send a Slack Notification
        if: always()
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: 'channel-git-actions'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
